version: "3.9"
services:
  location-classifier:
    image: zoomcamp-capstone-model:xception-v4-003
  gateway:
    image: zoomcamp-capstone-gateway:003
    environment:
      - TF_SERVING_HOST=location-classifier:8500
    ports:
      - "9696:9696"
