apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        # image: zoomcamp-capstone-gateway:003
        image: 939646755809.dkr.ecr.us-east-2.amazonaws.com/location-classifier-eks:zoomcamp-capstone-gateway-003
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9696
        env:
          - name: TF_SERVING_HOST
            value: location-classifier.default.svc.cluster.local:8500
